-- AlterTable
ALTER TABLE `assetrequest` MODIFY `status` ENUM('PENDING', 'APPROVED', 'PARTIALLY_ISSUED', 'ISSUED', 'REJECTED', 'RECIEVED', 'CLOSED') NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE `request` MODIFY `status` ENUM('PENDING', 'APPROVED', 'PARTIALLY_ISSUED', 'ISSUED', 'REJECTED', 'RECIEVED', 'CLOSED') NOT NULL DEFAULT 'PENDING';
