-- AlterTable
ALTER TABLE `assetrequest` MODIFY `status` ENUM('PENDING', 'APPROVED', 'REJECTED', 'ISSUED', 'PARTIALLY_ISSUED', 'CLOSED') NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE `assetrequestitem` ADD COLUMN `procurementStatus` ENUM('NOT_REQUIRED', 'REQUIRED', 'ORDERED', 'COMPLETED') NOT NULL DEFAULT 'NOT_REQUIRED',
    ADD COLUMN `quantityIssued` INTEGER NULL DEFAULT 0,
    ADD COLUMN `status` ENUM('PENDING', 'ISSUED', 'PARTIALLY_ISSUED', 'PENDING_PROCUREMENT') NOT NULL DEFAULT 'PENDING';
